version: "3.8"

services:
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    container_name: mariadb
    ports:
      - "${MARIADB_PORT}:3306"
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - mariadb
    image: wordpress:${WORDPRESS_VERSION}
    container_name: wordpress
    ports:
      - "${WORDPRESS_PORT}:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb:${MARIADB_PORT}
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

volumes:
    db_data: