version: "3.8"

services:
  homeassistant:
    image: "homeassistant/home-assistant:${HOMEASSISTANT_VERSION}"
    container_name: homeassistant
    ports:
      - "${HOMEASSISTANT_PORT}:8123"
    restart: unless-stopped
    privileged: true
